name: CI Client builder
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 8192
        base_image: raspios_lite_arm64:latest
        bind_mount_repository: true
        commands: |
            export MY_INSTALL_DIR=$HOME/.local
            mkdir -p $MY_INSTALL_DIR
            export PATH="$MY_INSTALL_DIR/bin:$PATH"
            apt update
            apt install -y sudo cmake git build-essential autoconf libtool pkg-config libjsoncpp-dev libpqxx-dev libc6 unzip ninja-build
            git clone https://github.com/Microsoft/vcpkg.git
            cd vcpkg
            export VCPKG_FORCE_SYSTEM_BINARIES=1
            ./bootstrap-vcpkg.sh -disableMetrics
            sudo ./vcpkg integrate install
            ./vcpkg install grpc && ./vcpkg install protobuf
            cd ..
            cd client/
            # https://superuser.com/a/246841
            echo 'set (VCPKG_HOME "$ENV{HOME}/vcpkg")' | cat - CMakeLists.txt > tmp && mv tmp CMakeLists.txt
            chmod +x genCppProto.sh
            ./genCppProto.sh
            mkdir -p cmake/build
            cd cmake/build
            cmake ../..
            make -j 2
            cd ../..
    - name: Upload binary release file
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: cmake/build/client
