name: CI Client builder
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        cpu: cortex-a7
        image_additional_mb: 8192
        commands: |
            export MY_INSTALL_DIR=$HOME/.local
            mkdir -p $MY_INSTALL_DIR
            export PATH="$MY_INSTALL_DIR/bin:$PATH"
            sudo apt update
            sudo apt install -y git build-essential autoconf libtool pkg-config libjsoncpp-dev libpqxx-dev
            wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.29.6/cmake-3.29.6-linux-aarch64.sh
            sh cmake-linux.sh -- --skip-license --prefix=$MY_INSTALL_DIR
            rm cmake-linux.sh
            ls $MY_INSTALL_DIR
            export PATH="$MY_INSTALL_DIR/cmake:$PATH"
            git clone --recurse-submodules -b v1.64.2 --depth 1 --shallow-submodules https://github.com/grpc/grpc
            cd grpc
            mkdir -p cmake/build
            cd cmake/build
            cmake -DgRPC_INSTALL=ON \
              -DgRPC_BUILD_TESTS=OFF \
              -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
              ../..
            make -j 3
            make install
            cd ../../../
            pwd
            ls
            mkdir -p cmake/build
            cd cmake/build
            cmake ../..
            make -j 3
            cd ../..
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: cmake/build/client